"""Generate shrunk copies of community card fixtures to simulate showdown size.

WePoker showdown reveals cards at 30-50% the size of community cards;
existing CNN (trained on ~60x90 px community fixtures) sees too few rank
pixels at inference time → rank_conf drops to 0.5-0.85.

This script generates synthetic "small card" versions by:
  1. Resampling each fixture down to scale × original (BILINEAR — same as real
     WePoker downscale path)
  2. Upsampling back to original dims (BILINEAR — same as trainer Resize at
     load time)

The roundtrip preserves dimensions but **destroys high-frequency detail** —
exactly the symptom of small showdown cards. Trainer treats these as ordinary
community-domain samples; the lost detail becomes implicit augmentation.

Originals in tests/fixtures/cards/ are NEVER touched. Output goes to a
separate directory tests/fixtures/cards_shrunk/. Re-running is idempotent:
existing output files are overwritten with the same content.

Usage:
    python tools/shrink_cards.py                       # default 0.5 + 0.7 scales
    python tools/shrink_cards.py --scales 0.4 0.6 0.8  # custom
    python tools/shrink_cards.py --dry-run             # preview without writing
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from PIL import Image

PROJ = Path(__file__).resolve().parent.parent
SRC_DIR = PROJ / "tests" / "fixtures" / "cards"
DST_DIR = PROJ / "tests" / "fixtures" / "cards_shrunk"


def _scale_tag(s: float) -> str:
    """0.5 -> s05, 0.65 -> s065. Filename-safe."""
    return "s" + str(s).replace(".", "").lstrip("0") or "s0"


def shrink_one(png: Path, scale: float, dst_dir: Path, dry_run: bool = False) -> tuple[Path, dict]:
    img = Image.open(png).convert("RGB")
    w, h = img.size
    sw, sh = max(1, int(round(w * scale))), max(1, int(round(h * scale)))
    # Shrink → upscale roundtrip; both BILINEAR to match trainer Resize behavior
    shrunk = img.resize((sw, sh), Image.BILINEAR)
    out = shrunk.resize((w, h), Image.BILINEAR)

    src_json = png.with_suffix(".json")
    meta = json.loads(src_json.read_text(encoding="utf-8")) if src_json.exists() else {}
    meta = {
        **meta,
        "source_fixture": png.name,
        "shrink_scale": scale,
        "synthetic": True,
        "note": "Generated by tools/shrink_cards.py — DO NOT manually edit",
    }

    tag = _scale_tag(scale)
    dst_png = dst_dir / f"{png.stem}_{tag}.png"
    dst_json = dst_dir / f"{png.stem}_{tag}.json"
    if not dry_run:
        out.save(dst_png, format="PNG")
        dst_json.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    return dst_png, meta


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--scales", type=float, nargs="+", default=[0.5, 0.7],
                    help="Shrink factors (default: 0.5 0.7)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Preview file counts without writing")
    ap.add_argument("--clean", action="store_true",
                    help="Remove existing cards_shrunk/ before generating")
    args = ap.parse_args()

    if not SRC_DIR.exists():
        print(f"✗ Source not found: {SRC_DIR}", file=sys.stderr)
        return 1

    pngs = sorted(SRC_DIR.glob("*.png"))
    if not pngs:
        print(f"✗ No PNGs in {SRC_DIR}", file=sys.stderr)
        return 1

    if args.clean and DST_DIR.exists() and not args.dry_run:
        print(f"Cleaning existing {DST_DIR}")
        shutil.rmtree(DST_DIR)

    if not args.dry_run:
        DST_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Source: {SRC_DIR}  ({len(pngs)} fixtures)")
    print(f"Dest:   {DST_DIR}")
    print(f"Scales: {args.scales}")
    print(f"Will generate: {len(pngs) * len(args.scales)} new files\n")

    n = 0
    for png in pngs:
        for s in args.scales:
            dst_png, meta = shrink_one(png, s, DST_DIR, dry_run=args.dry_run)
            n += 1
            if n <= 3 or n == len(pngs) * len(args.scales):
                print(f"  {'(dry)' if args.dry_run else '✓'} {dst_png.relative_to(PROJ)}  "
                      f"scale={s}  rank={meta.get('expected',{}).get('rank')} "
                      f"suit={meta.get('expected',{}).get('suit')}")

    print(f"\nDone. {n} {'would be ' if args.dry_run else ''}written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
